/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HEIFConverter */

#ifndef _Included_HEIFConverter
#define _Included_HEIFConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HEIFConverter
 * Method:    convert
 * Signature: (I[BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_HEIFConverter_convert
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
  